services:
  - type: web
    name: text-to-speech-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --workers 4 --worker-class aiohttp.worker.GunicornWebWorker
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
